trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  CI: 'true'

steps:
  - checkout: self

  - task: NodeTool@0
    displayName: Usar Node.js 20
    inputs:
      versionSpec: 20.x

  - script: npm ci
    displayName: Instalar dependencias

  - script: npx playwright install --with-deps chromium
    displayName: Instalar Chromium

  - script: npm run typecheck
    displayName: Validar TypeScript

  - script: npm test
    displayName: Ejecutar pruebas Playwright

  - task: PublishTestResults@2
    displayName: Publicar resultados JUnit
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: test-results/junit.xml
      failTaskOnFailedTests: true
      testRunTitle: Pruebas OrangeHRM

  - task: PublishPipelineArtifact@1
    displayName: Publicar reporte HTML
    condition: succeededOrFailed()
    inputs:
      targetPath: playwright-report
      artifact: playwright-report
      publishLocation: pipeline

  - task: PublishPipelineArtifact@1
    displayName: Publicar evidencias
    condition: succeededOrFailed()
    inputs:
      targetPath: test-results
      artifact: test-results
      publishLocation: pipeline
